# Generated by Django 4.1.4 on 2023-01-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeighBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wgid', models.CharField(max_length=20, unique=True)),
                ('location', models.CharField(max_length=50)),
                ('added_by', models.CharField(default='Admin', max_length=100)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
