# Generated by Django 4.1.4 on 2023-01-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weighing', '0002_temprakedetails_tempwagondetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempwagondetails',
            name='wgTare',
            field=models.FloatField(),
        ),
    ]
