# Generated by Django 4.1.4 on 2023-01-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weighing', '0003_alter_tempwagondetails_wgtare'),
    ]

    operations = [
        migrations.AddField(
            model_name='temprakedetails',
            name='wgid',
            field=models.CharField(default='', max_length=20),
        ),
    ]
