# Generated by Django 4.1.4 on 2023-01-27 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weighing', '0006_permrakedetails_isuploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permwagondetails',
            name='rakeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weighing.permrakedetails'),
        ),
    ]
