# Generated by Django 4.1.4 on 2023-01-27 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weighing', '0007_alter_permwagondetails_rakeid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permwagondetails',
            old_name='moOfAxles',
            new_name='noOfAxles',
        ),
    ]
