# Generated by Django 4.1.4 on 2023-01-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weighing', '0008_rename_moofaxles_permwagondetails_noofaxles'),
    ]

    operations = [
        migrations.AddField(
            model_name='permrakedetails',
            name='totalNetWt',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='permrakedetails',
            name='uploadTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='permrakedetails',
            name='weightmentTime',
            field=models.DateTimeField(null=True),
        ),
    ]
