# Generated by Django 4.1.4 on 2023-09-04 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weighing', '0009_permrakedetails_totalnetwt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permrakedetails',
            name='commodity',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='permrakedetails',
            name='direction',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='permrakedetails',
            name='serialNo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='permwagondetails',
            name='WagonWeighingTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='weighbridge',
            name='cloud_ver',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='weighbridge',
            name='scada_ver',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='weighbridge',
            name='wg_ver',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
