# Generated by Django 4.1.4 on 2023-09-05 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weighing', '0011_alter_permwagondetails_wagonweighingtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='wgidSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading1', models.CharField(default='MBMH', max_length=200)),
                ('heading2', models.CharField(default='HO', max_length=200)),
                ('heading3', models.CharField(default='WAG9 UNV TESTING 5.9.0', max_length=200)),
                ('stationName', models.CharField(default='MERIT', max_length=100)),
                ('minNetWtForUL_Cal', models.FloatField(default=2.0)),
                ('commodity', models.CharField(max_length=100, null=True)),
                ('srcStation', models.CharField(max_length=100, null=True)),
                ('tareWt_manual', models.BooleanField(default=True)),
                ('overLoadExceed', models.FloatField(default=0.0)),
                ('underLoadIfLess', models.FloatField(default=0.0)),
                ('signature1', models.CharField(max_length=200, null=True)),
                ('signature2', models.CharField(max_length=200, null=True)),
                ('printSummary', models.BooleanField(default=True)),
                ('printReportAuto', models.BooleanField(default=False)),
                ('weighController', models.CharField(default='Remote ScoreBoard', max_length=100)),
                ('wgid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weighing.weighbridge')),
            ],
        ),
    ]
