# Generated by Django 4.1.4 on 2023-09-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weighing', '0012_wgidsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='weighbridge',
            name='cloudReleaseDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='weighbridge',
            name='scadaReleaseDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='weighbridge',
            name='wgReleaseDate',
            field=models.DateTimeField(null=True),
        ),
    ]
