# Generated by Django 4.1.4 on 2023-09-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weighing', '0013_weighbridge_cloudreleasedate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permwagondetails',
            name='cc',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='permwagondetails',
            name='pcc',
            field=models.FloatField(default=0.0),
        ),
    ]
