# Generated by Django 4.1.4 on 2023-09-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weighing', '0014_permwagondetails_cc_permwagondetails_pcc'),
    ]

    operations = [
        migrations.AddField(
            model_name='permrakedetails',
            name='billingLine1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='permrakedetails',
            name='billingLine2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='permrakedetails',
            name='billingLine3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='permrakedetails',
            name='operatorName',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
