# Generated by Django 4.1.4 on 2023-09-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weighing', '0015_permrakedetails_billingline1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permwagondetails',
            name='WagonWeighingTime',
            field=models.DateTimeField(null=True),
        ),
    ]
