# Generated by Django 4.1.4 on 2023-09-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weighing', '0016_alter_permwagondetails_wagonweighingtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weighbridge',
            name='date_joined',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='weighbridge',
            name='scadaReleaseDate',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='weighbridge',
            name='wgReleaseDate',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
